---
apiVersion: v1
kind: Service
metadata:
  name: hgb-front-service
  namespace: hgb-fe
  labels:
    app: hgb-front
    istio-injection: enabled
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: hgb-front

