apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hgb-front
  namespace: hgb-fe
spec:
  selector:
    matchLabels:
      app: hgb-front
  replicas: 1
  template:
    metadata:
      labels:
        app: hgb-front
        istio-injection: enabled
    spec:
      containers:
        - name: test
          image: vulcanos/hgb-fe:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "3000m"
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: VUE_APP_API_URL
              value: "http://hgb-backend-service.hgb-backend.svc.cluster.local/api/v1/steam/pricev2?item_id="
#          envFrom:
#            - secretRef:
#                name: hgb-server-secret
  serviceName: hgb-front-service